spring:
  application:
    name: outsourcing-project
  profiles:
    include: private
  jpa:
    properties:
      hibernate:
#        ddl-auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
#    generate-ddl: true

